### ISSUE TITLE
What if I wanna use both callback and view controller when mapping?

### ISSUE THREAD

**Issue by luna-moonfang** [clayallsopp/routable-ios#39]
For example, I open specific view controller and then perform some code in callback block for the mapping URL.
I read the code and found that you can only do one of the callback and view controller and return.

**Comment by clayallsopp** [comment]
Yup, and I think that's the opinion of this library - anything more particular is too domain-specific

in cases like these, I recommend using a callback and manually controlling your view controller logic based on the provided URL + params

**Comment by luna-moonfang** [comment]
Thanks. Your suggestion is exactly what I am doing.
