### ISSUE TITLE
Any plans for an 0.1.2 release?

### ISSUE THREAD

**Issue by jrmiddle** [clayallsopp/routable-ios#41]
Hi, just curious—any plan to cut a 0.1.2 with @NorthStar 's (and others') changes included? ATM I'm using :head in my Podfile which always makes me nervous.

Thanks!

**Comment by clayallsopp** [comment]
@jrmiddle I pushed a 0.2.0 tag, currently working on getting the Pod updated: https://github.com/CocoaPods/trunk.cocoapods.org/issues/146

**Comment by jrmiddle** [comment]
Awesome, thanks Clay!

Sent from mobile.
All times PDT/GMT-7 unless otherwise specified.

**Comment by clayallsopp** [comment]
@jrmiddle I've pushed 0.2.0: https://cocoapods.org/pods/Routable
