### ISSUE TITLE
Multiple mappings do not consider each other

### ISSUE THREAD

**Issue by johosher** [clayallsopp/routable-ios#42]
I am trying to map multiple URLs to the same controller but the router just uses the first one it finds.  Consider opening the following URL in the example below: "example/new/test".  
    
    [[Routable sharedRouter] map:@"example/new/:param1" toController:[Example class]];
    [[Routable sharedRouter] map:@"example/:param1/:param2" toController:[Example class]];

What I would expect to happen is my controller will be initialized with the first mapping and param1 being set to "test" but it actually opens the second mapping with param1 being set to "new" and param2 being set to "test".  I believe this is a caching issue and it doesn't consider all scenarios of the mappings.  

Any advice? Thanks!

**Comment by clayallsopp** [comment]
Yup, Routable doesn't explicitly handle route format collisions like that (and I'd not sure it'd be worth it - it would end up confusing one group of people or the other). I'd suggest doing something like `example-new/:param1` and `example/:param1/:param2` to get the exact behavior you want

**Comment by johosher** [comment]
Not sure why it wouldn't be worth it since you could use some sort of priority system.  

Switching to [JLRoutes](https://github.com/joeldev/JLRoutes) for this and query params support.

**Comment by NorthStar** [comment]
Let's be 'friendly and patient', which the open code of conduct calls for.
Since Clay is the lone owner and maintainer, requesting him to do work for
you is a bit mean.

Meanwhile, since routable is MIT licensed, you are free to modify it in
your own implementation (and send PRs if you want to contribute back).

Thanks,
-Mimee

**Comment by johosher** [comment]
I wasn't trying to be unfriendly (now that I re-read it I can see why one would think that) just merely suggesting how to improve it and giving another option for people who see this and want that functionality. All is good yo!
